name: Compile AHK v2 Script

on:
  push:
    branches: [ add-gh-workflow ]
  workflow_dispatch:

jobs:
  compile-ahk:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download AHK v2 Compiler
      run: |
        curl -L "https://github.com/AutoHotkey/AutoHotkey/releases/download/v2.0.10/AutoHotkey_2.0.10_setup.exe" -o "$env:TEMP\ahk_installer.exe"
        start /wait "$env:TEMP\ahk_installer.exe" /S

    - name: Find AHK Compiler
      run: |
        $ahkCompiler = "$env:ProgramFiles\AutoHotkey\Compiler\Ahk2Exe.exe"
        if (-not (Test-Path $ahkCompiler)) {
          $ahkCompiler = "${env:ProgramFiles(x86)}\AutoHotkey\Compiler\Ahk2Exe.exe"
        }
        echo "AHK_COMPILER=$ahkCompiler" >> $env:GITHUB_ENV

    - name: Compile AHK script to EXE
      run: |
        # Find the first .ahk file in the repository if not specified
        $ahkScript = Get-ChildItem -Path . -Filter *.ahk | Select-Object -First 1
        if (-not $ahkScript) {
          Write-Error "No .ahk file found in the repository"
          exit 1
        }

        $outputExe = "$($ahkScript.BaseName).exe"
        & "$env:AHK_COMPILER" /in "$($ahkScript.FullName)" /out "$outputExe"

        # Verify the output file was created
        if (-not (Test-Path $outputExe)) {
          Write-Error "Compilation failed - output file not created"
          exit 1
        }

    - name: Upload Release Asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "*.exe"
        asset_name: ahk-scrobbler.exe
        asset_content_type: application/octet-stream
